### ISSUE TITLE
Killed by signal 9 Problem about running HPL test of MKL in intel/oneapi-hpckit docker container

### ISSUE THREAD

**Issue by zhangshuiyong** [oneapi-src/oneMKL#124]
I want to run hpl test script in docker container. I run the container like below the command:

`
docker run -d  --privileged -it intel/oneapi-hpckit
`

Then, I enter the container, run the below command:

`$ cd /opt/intel/oneapi`
`$ source setvars.sh --force`
`$ cd /opt/intel/oneapi/mkl/latest/benchmarks/mp_linpack`
`$ ./runme_intel64_dynamic`

When i am running hpl test of mkl in intel/oneapi-hpckit docker container，it will occur error like the below:

![image](https://user-images.githubusercontent.com/1655233/131518155-cb4ce911-5680-415d-8585-a627b014e970.png)

My docker info like the below:
![image](https://user-images.githubusercontent.com/1655233/131518467-c739055f-8e30-4b99-bde2-af4baa4e8109.png)

My HPL.dat file like the below:
![image](https://user-images.githubusercontent.com/1655233/131518611-35d67cf9-f7ca-4e1e-a0a4-1201fd89751c.png)

**Comment by jasukhar** [comment]
Hi @zhangshuiyong! Thanks for bringing this issue! However this issue is not related to oneMKL interfaces open source project but to our binary product which is not covered here.
To submit issue against Intel(R) oneMKL binary product please use the forum: https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/bd-p/oneapi-math-kernel-library
To learn about differences between oneMKL interfaces open source project, Intel(R) oneMKL product and oneMKL spec, please see our [FAQ](https://github.com/oneapi-src/oneMKL#faqs)

**Comment by zhangshuiyong** [comment]
@jasukhar Thx for your Info.
