### ISSUE TITLE
Use LLVM libomp as the threading layer

### ISSUE THREAD

**Issue by Jerry-Ma** [oneapi-src/oneMKL#132]
Hi,

I am using Intel oneAPI 2021.3 and it comes with a MKLConfig.cmake file that allows customized importing of MKL::MKL target.

However, when on macOS with brew installed llvm and libomp, the MKLConfig.cmake does not recognize the `libomp` as an option for the threading layer:

```
-- MKL_ARCH: intel64
-- MKL_LINK: static
-- MKL_INTERFACE_FULL: intel_lp64
CMake Error at /usr/local/lib/cmake/mkl-2021.3.0/MKLConfig.cmake:154 (message):
  Invalid MKL_THREADING `gnu_thread`, options are: sequential intel_thread
  tbb_thread
Call Stack (most recent call first):
  /usr/local/lib/cmake/mkl-2021.3.0/MKLConfig.cmake:326 (define_param)
  CMakeLists.txt:31 (find_package)
```

Inspecting the relevant section of code in MKLConfig.cmake, I found it checks only the GNU compiler, not LLVM:

```
<omitted>
if(DPCPP_COMPILER)
  set(DEFAULT_MKL_THREADING tbb_thread)
  list(REMOVE_ITEM MKL_THREADING_LIST intel_thread)
# C, Fortran API
elseif(PGI_COMPILER)
  # PGI compiler supports PGI OpenMP threading, additionally
  list(APPEND MKL_THREADING_LIST pgi_thread)
  # PGI compiler does not support TBB threading
  list(REMOVE_ITEM MKL_THREADING_LIST tbb_thread)
  if(WIN32)
    # PGI 19.10 and 20.1 on Windows, do not support Intel OpenMP threading
    list(REMOVE_ITEM MKL_THREADING_LIST intel_thread)
    set(DEFAULT_MKL_THREADING pgi_thread)
  endif()
elseif(GNU_C_COMPILER OR GNU_Fortran_COMPILER)
  list(APPEND MKL_THREADING_LIST gnu_thread)
else()
  # Intel and Microsoft compilers
  # Nothing to do, only for completeness
endif()
define_param(MKL_THREADING DEFAULT_MKL_THREADING MKL_THREADING_LIST)
<omitted>
```

Also, I found this online link line advisor https://software.intel.com/content/www/us/en/develop/tools/oneapi/components/onemkl/link-line-advisor.html
which does not provide the option of using LLVM Clang either.

So, my question is, is it supported to use the LLVM libomp + LLVM Clang + intel MKL? If so, what would be the link line?

**Comment by jasukhar** [comment]
Hi @Jerry-Ma !
Thanks for bringing this issue! However this issue is not related to oneMKL interfaces open source project but to our binary product which is not covered here.
To submit issue against Intel(R) oneMKL binary product please use the forum: https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/bd-p/oneapi-math-kernel-library
To learn about differences between oneMKL interfaces open source project, Intel(R) oneMKL product and oneMKL spec, please see our [FAQ](https://github.com/oneapi-src/oneMKL#faqs)
However, I can confirm that so far we haven't officially supported clang compiler and the support will be added to oneMKL 2022.0

**Comment by Jerry-Ma** [comment]
Thanks a lot for the detailed answer! I'll post the question in the forum then. I think this can be closed now. Thank you!
