### ISSUE TITLE
Segmentation fault of "oneapi::mkl::blas::column_major::gemm" call on CUDA backend.

### ISSUE THREAD

**Issue by tangjj11** [oneapi-src/oneMKL#296]
# Summary
Segmentation fault of "oneapi::mkl::blas::column_major::gemm" call on CUDA backend.

# Version
20230223 (mkl_nightly_2023u1_20230223_lnx)

# Environment
NVIDIA Corporation GA102 [GeForce RTX 3090]
Ubuntu 22.04
sycl compiler: 20230321_160000 (c5c7ac2ea55b23c019120885174a6a10f1506282)

# Steps to reproduce
[main.dp.cpp.txt](https://github.com/oneapi-src/oneMKL/files/11095531/main.dp.cpp.txt)
export SYCL_DEVICE_FILTER="CUDA:GPU"
clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda main.dp.cpp -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lOpenCL -lmkl_sycl
./a.out

# Observed behavior
command output:
tjj 0
tjj 1

WARNING: The enviroment variable SYCL_DEVICE_FILTER is deprecated. Please use ONEAPI_DEVICE_SELECTOR instead.
For more details, please refer to:
https://github.com/intel/llvm/blob/sycl/sycl/doc/EnvironmentVariables.md#oneapi_device_selector

tjj 2
tjj 3
tjj 4
Segmentation fault (core dumped)

# Expected behavior
command output (if use cpu by export SYCL_DEVICE_FILTER="CPU"):
tjj 0
tjj 1

WARNING: The enviroment variable SYCL_DEVICE_FILTER is deprecated. Please use ONEAPI_DEVICE_SELECTOR instead.
For more details, please refer to:
https://github.com/intel/llvm/blob/sycl/sycl/doc/EnvironmentVariables.md#oneapi_device_selector

tjj 2
tjj 3
tjj 4
tjj 5

**Comment by HaoweiZhangIntel** [comment]
Hi, I tested your code with compilation towards CUDA backend. It works fine on my machine with Titan V gpu.
I guess your problem is caused by the inappropriate version/build of oneMKL.
Below is my solution:
First, I clone the latest develop branch of oneMKL and build it with cmake:
```
$ mkdir build && cd build
```
```
$ cmake -DCMAKE_CXX_COMPILER=clang++ \
-DCMAKE_C_COMPILER=clang \
-DENABLE_CUBLAS_BACKEND=TRUE \
-DENABLE_CUSOLVER_BACKEND=TRUE \
-DENABLE_CURAND_BACKEND=TRUE \
-DENABLE_MKLCPU_BACKEND=FALSE \
-DENABLE_MKLGPU_BACKEND=FALSE \
-DBUILD_FUNCTIONAL_TESTS=FALSE \
-DCMAKE_BUILD_TYPE=Release \
-BUILD_DOC=TRUE \
-DCMAKE_INSTALL_PREFIX=/path_to_oneMKL/build/install/ \
..
```
```
$ cd UILD_DOC\=TRUE
```
```
$ make -j
```
```
$ ctest
```
```
$ make install .
```

Then set the environment as:
```
$ export MKLROOT=/path_to_oneMKL/build/install/
```
```
$ export LD_LIBRARY_PATH=${MKLROOT}/lib/:$LD_LIBRARY_PATH
```

Finally, I compiled you test case for CUDA backend and ran it on Titan V:
```
$ clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda -Xsycl-target-backend=nvptx64-nvidia-cuda --cuda-gpu-arch=sm_70 -I${MKLROOT}/include -L${MKLROOT}/lib -lonemkl -lonemkl_blas_cublas -lonemkl_lapack_cusolver main.cp.cpp
```
```
$ export SYCL_DEVICE_FILTER=[ext_oneapi_cuda:gpu:0]
```
```
$ ./a.out
```

The clang++ is the llvm component of oneAPI for NVIDIA GPUs, you can download from codeplay and install/setup it based on oneAPI Base toolkit 2023 as the following method:
[https://developer.codeplay.com/products/oneapi/nvidia/2023.0.0/guides/get-started-guide-nvidia](url)

This is my test ouput for your code:
![image](https://user-images.githubusercontent.com/109200794/228404554-aa3ff4f9-1d97-42c3-b356-aaaf6b8c3573.png)
