### ISSUE TITLE
Building Failure

### ISSUE THREAD

**Issue by Lang0722** [oneapi-src/oneMKL#334]
I was buiding this for the cuda backend using cmake
Using command: `cmake .. -DCMAKE_CXX_COMPILER=/opt/intel/oneapi/compiler/latest/linux/bin-llvm/clang++ \
         -DCMAKE_C_COMPILER=/opt/intel/oneapi/compiler/latest/linux/bin-llvm/clang \
         -DENABLE_CUBLAS_BACKEND=True  \
         -DENABLE_CUSOLVER_BACKEND=True \
         -DENABLE_CURAND_BACKEND=True   \
         -DENABLE_NETLIB_BACKEND=False   \
         -DREF_BLAS_ROOT=/usr/local`
Cmake report the problem
`Could NOT find LAPACKE (missing: CBLAS64_file)`
I have already installed the LAPACKE using cmake into both /local/usr and $HOME/.local/lapack/

Someone have ideas about how to solve this? Thanks

**Comment by Lang0722** [comment]
I have slove this problem by buidling the LAPACKET with BUILD_INDEX64=ON and setting BUILD_SHARED_LIBS=ON and CBLAS= ON

**Comment by FMarno** [comment]
Hi @Lang0722,
Some pointers that might help for the future:
* you can select which domains to use with the `TARGET_DOMAINS` variable, this is a list of domains separated by `;`. The options are `blas`, `dft`, `rng`, and `lapack`. I think you want `-DTARGET_DOMAINS="blas;lapack"`.
* I don't think you need `REF_BLAS_ROOT` unless you are contributing to oneMKL
* `ENABLE_MKLGPU_BACKEND` and `ENABLE_MKLCPU_BACKEND` are enabled by default, so if you only want the cuda libraries then you can turn those off.  It does sound like you have the libraries though.

Without setting the `TARGET_DOMAINS`, and leaving `ENABLE_MKLGPU_BACKEND`/`ENABLE_MKLCPU_BACKEND`, all the Intel libraries are enabled so that might have been causing your issue.
