### ISSUE TITLE
SGEMV bf16/int8 support

### ISSUE THREAD

**Issue by akote123** [oneapi-src/oneMKL#596]
Is there any support for sgemv int8/bf16 in mkl?

In mkl_blas.h file I was not able to find any apis for bf16/int8 sgemv ,Is there any  reason of not having the int8sgemv kernel?

**Comment by Rbiessy** [comment]
Since you mention `mkl_blas.h` it looks like you are talking about Intel's oneMKL product which is a different project, see the FAQ: https://github.com/oneapi-src/oneMKL?tab=readme-ov-file#onemkl.
If you are asking for the Intel oneMKL product to add support for these types then this should be asked in the Intel forum: https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/bd-p/oneapi-math-kernel-library. Once the Intel backends support these types we could add support for them in oneMKL Interface too.

**Comment by Rbiessy** [comment]
Closing as the question has been answered. Feel free to re-open if you have more questions.
